name: Continuous Integration

on: push

env:
    CARGO_TERM_COLOR: always

jobs:
    ci:
        runs-on: ubuntu-latest
        name: Continuous Integration
        steps:
            - uses: actions/checkout@v4
            # Set up Rust with nightly
            - name: Install Rust nightly
              uses: actions-rs/toolchain@v1
              with:
                toolchain: nightly
                profile: minimal # Optionally use "default" or "complete" for additional components
                override: true  # Makes nightly the default version for this workflow

            - name: Set up cargo cache
              uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-cargo-
            - name: cargo test
              run: cargo test
            # uncomment to enable clippy linter
            # - name: cargo clippy
            #   run: cargo clippy -- -D warnings
            # uncomment to enable format linter
            # - name: cargo fmt
            #   run: cargo fmt --check
